name: nf_cloud
dependencies:
  - libpq
  - nodejs=14.*
  - yarn
  - python=3.10
  - pip
  - setuptools
  - cython
  - yaml
  - pip:
    - eventlet  >=0.33, <0.34
    - Flask  >=1, <2
    - Flask-Caching  >=2, <3
    - Flask-Cors  >=3, <4
    - Flask-Login  >=0.6.1, <0.7.0
    - flask-socketio  >=5, <6
    - kombu  >=5, <6
    - markupsafe  ==2.0.1      # fix for `ImportError: cannot import name 'soft_unicode'`
    - mergedeep  >=1, <2
    - oauthlib  >=3, <4
    - peewee  >=3, <4
    - peewee-migrate  >=1.1.6
    - pika  >=1, <2
    - piwikapi  ==0.3
    - psycopg2-binary  >=2, <3
    - pyjwt  >=2, <3
    - PyYAML >=5, <6 --install-option='--with-libyaml'
    - requests  >=2, <3
    - zipstream-new  >=1, <2
    # Dev dependencies
    - honcho
    - pylint
    - requests
